### ISSUE TITLE
Migrar de SQLite a Posgres SQL

### ISSUE THREAD

**Issue by Akatsuki507** [Spidey507/railsapp1#14]
# Current behavior
Se esta usando SQLite durante el desarrollo del app, y esto hace menos escalable el tema de conservar los datos.

# Expected behavior
Se espera que el desarrollo del app cambie a posgreSQL conservando los indices de las tablas, y sin conservar los datos ya que son de prueba.

# Links de ayuda
- https://medium.com/@virtual_khan/converting-rails-from-sqlite3-to-postgresql-d97023314a14
- https://medium.com/@thorntonbrenden/ruby-on-rails-switch-from-sqlite3-to-postgres-590009645c25

**Comment by Spidey507** [comment]
Cerrado bajo la pull request #19
