### ISSUE TITLE
Crear una vista perfil del usuario 

### ISSUE THREAD

**Issue by Akatsuki507** [Spidey507/railsapp1#17]
# Current behavior 
No existe.

# Expected behavior
Se requiere una pantalla desde la cual el usuario pueda ver su informacion personal registrada, la lista de sus articulos asociados, la lista de sus comentarios asociados.

# Links de ayuda
- https://guides.rubyonrails.org/action_controller_overview.html

Depends on #15 , #16

**Comment by Spidey507** [comment]
Resuelto bajo la PR #22
